import { describe, it, expect, afterAll } from 'vitest';
import { generatePDF, generatePDFToFile, generateSolarProposalPDF, closeBrowser } from './pdf';
import fs from 'fs/promises';
import path from 'path';

describe('Puppeteer PDF Generation', () => {
  const testOutputDir = '/tmp';

  afterAll(async () => {
    // Close browser after all tests
    await closeBrowser();
  });

  it('should generate a simple test PDF', async () => {
    const html = `
      <!DOCTYPE html>
      <html>
        <head>
          <title>Solar Qualifier Test</title>
          <style>
            body { font-family: Arial, sans-serif; padding: 40px; background: #f5f5f5; }
            .container { background: white; padding: 40px; border-radius: 8px; }
            h1 { color: #667eea; }
            p { line-height: 1.6; color: #333; }
          </style>
        </head>
        <body>
          <div class="container">
            <h1>Solar Qualifier Test</h1>
            <p>This is a test PDF generated by Puppeteer.</p>
            <p>Generated: ${new Date().toISOString()}</p>
            <p>This confirms that PDF generation is working correctly.</p>
          </div>
        </body>
      </html>
    `;

    const result = await generatePDF({
      html,
      filename: 'test.pdf',
      format: 'A4',
    });

    expect(result.success).toBe(true);
    expect(result.buffer).toBeDefined();
    expect(result.buffer!.length).toBeGreaterThan(0);

    console.log(`[Test] ✓ PDF generated: ${result.buffer!.length} bytes`);
  });

  it('should save PDF to file', async () => {
    const html = `
      <!DOCTYPE html>
      <html>
        <head>
          <title>Solar Qualifier Test</title>
          <style>
            body { font-family: Arial, sans-serif; padding: 40px; }
            h1 { color: #667eea; }
          </style>
        </head>
        <body>
          <h1>Solar Qualifier Test</h1>
          <p>This PDF was saved to disk.</p>
        </body>
      </html>
    `;

    const outputPath = path.join(testOutputDir, 'test.pdf');

    const result = await generatePDFToFile(
      {
        html,
        filename: 'test.pdf',
        format: 'A4',
      },
      outputPath
    );

    expect(result.success).toBe(true);
    expect(result.filePath).toBe(outputPath);

    // Verify file exists
    const fileStats = await fs.stat(outputPath);
    expect(fileStats.isFile()).toBe(true);
    expect(fileStats.size).toBeGreaterThan(0);

    console.log(`[Test] ✓ PDF saved: ${outputPath} (${fileStats.size} bytes)`);

    // Cleanup
    await fs.unlink(outputPath);
  });

  it('should generate solar proposal PDF', async () => {
    const leadData = {
      companyName: 'Solar Tech Inc',
      address: '789 Energy Lane, Berlin, Germany',
      email: 'info@solartech.de',
      avgBillEur: 7500,
    };

    const result = await generateSolarProposalPDF(leadData);

    expect(result.success).toBe(true);
    expect(result.buffer).toBeDefined();
    expect(result.buffer!.length).toBeGreaterThan(0);

    console.log(`[Test] ✓ Solar proposal PDF generated: ${result.buffer!.length} bytes`);
  }, { timeout: 15000 });

  it('should handle custom margins and format', async () => {
    const html = `
      <!DOCTYPE html>
      <html>
        <body>
          <h1>Custom Format Test</h1>
          <p>This PDF uses custom margins and Letter format.</p>
        </body>
      </html>
    `;

    const result = await generatePDF({
      html,
      filename: 'custom.pdf',
      format: 'Letter',
      margin: {
        top: 50,
        bottom: 50,
        left: 30,
        right: 30,
      },
    });

    expect(result.success).toBe(true);
    expect(result.buffer!.length).toBeGreaterThan(0);

        console.log(`[Test] ✓ Custom format PDF generated: ${result.buffer!.length} bytes`);

  }, { timeout: 15000 });

  it('should generate multiple PDFs sequentially', async () => {
    const results = [];

    for (let i = 0; i < 3; i++) {
      const html = `
        <html>
          <body>
            <h1>PDF ${i + 1}</h1>
            <p>Sequential PDF generation test</p>
          </body>
        </html>
      `;

      const result = await generatePDF({
        html,
        filename: `sequential-${i + 1}.pdf`,
      });

      results.push(result);
      expect(result.success).toBe(true);
    }

    console.log(`[Test] ✓ Generated ${results.length} PDFs sequentially`);
  }, { timeout: 30000 });
});
