import { describe, it, expect, afterAll } from 'vitest';
import { generatePDF, generatePDFToFile, generateSolarProposalPDF, closeBrowser } from './pdf';

describe('Puppeteer PDF Generation', () => {
  afterAll(async () => {
    // Close browser after all tests
    await closeBrowser();
  });

  it('should generate a simple test PDF', async () => {
    const html = `
      <!DOCTYPE html>
      <html>
        <head>
          <title>Solar Qualifier Test</title>
          <style>
            body { font-family: Arial, sans-serif; padding: 40px; background: #f5f5f5; }
            .container { background: white; padding: 40px; border-radius: 8px; }
            h1 { color: #667eea; }
            p { line-height: 1.6; color: #333; }
          </style>
        </head>
        <body>
          <div class="container">
            <h1>Solar Qualifier Test</h1>
            <p>This is a test PDF generated by Puppeteer.</p>
            <p>Generated: ${new Date().toISOString()}</p>
            <p>This confirms that PDF generation is working correctly.</p>
          </div>
        </body>
      </html>
    `;

    const result = await generatePDF({
      html,
      filename: 'test.pdf',
      format: 'A4',
    });

    expect(result.success).toBe(true);
    expect(result.buffer).toBeDefined();
    expect(result.buffer!.length).toBeGreaterThan(0);

    console.log(`[Test] ✓ PDF generated: ${result.buffer!.length} bytes`);
  });

  it('should return PDF as in-memory Buffer', async () => {
    const html = `
      <!DOCTYPE html>
      <html>
        <head>
          <title>Solar Qualifier Test</title>
          <style>
            body { font-family: Arial, sans-serif; padding: 40px; }
            h1 { color: #667eea; }
          </style>
        </head>
        <body>
          <h1>Solar Qualifier Test</h1>
          <p>This PDF is returned as an in-memory Buffer.</p>
        </body>
      </html>
    `;

    const result = await generatePDFToFile({
      html,
      filename: 'test.pdf',
      format: 'A4',
    });

    expect(result.success).toBe(true);
    expect(result.buffer).toBeDefined();
    expect(result.buffer!.length).toBeGreaterThan(0);
    expect(result.buffer).toBeInstanceOf(Buffer);

    console.log(`[Test] ✓ PDF returned as Buffer: ${result.buffer!.length} bytes`);
  });

  it('should generate solar proposal PDF', async () => {
    const solarData = {
      building: {
        maxPanels: 86,
        roofAreaM2: 291.26,
        maxSunshineHours: 1233.87,
        imageryDate: '2023-06-15',
        imageryQuality: 'HIGH',
      },
      financial: {
        currency: 'RON',
        systemKwp: 34.4,
        annualProductionKwh: 40687.145,
        annualSavingsRON: 34584.07,
        systemCostRON: 172000,
        governmentIncentiveRON: 20000,
        netCostRON: 152000,
        paybackYears: 4.4,
        savings20YearsRON: 519681.4,
        solarCoveragePct: 85,
      },
    };

    const result = await generateSolarProposalPDF('John Doe', 'Acme Corp', solarData, 'ro');

    expect(result.success).toBe(true);
    expect(result.buffer).toBeDefined();
    expect(result.buffer!.length).toBeGreaterThan(0);

    console.log(`[Test] ✓ Solar proposal PDF generated: ${result.buffer!.length} bytes`);
  });

  it('should include Yield Bureau branding in PDF', async () => {
    const html = `
      <!DOCTYPE html>
      <html>
        <head>
          <title>Branding Test</title>
        </head>
        <body>
          <h1>Branding Test</h1>
          <p>This PDF should include Yield Bureau branding.</p>
        </body>
      </html>
    `;

    const result = await generatePDF({
      html,
      format: 'A4',
    });

    expect(result.success).toBe(true);
    expect(result.buffer).toBeDefined();
    expect(result.buffer!.length).toBeGreaterThan(0);

    console.log(`[Test] ✓ PDF with branding generated: ${result.buffer!.length} bytes`);
  });

  it('should handle PDF generation errors gracefully', async () => {
    const invalidHtml = ''; // Empty HTML

    const result = await generatePDF({
      html: invalidHtml,
      format: 'A4',
    });

    // Should still succeed even with minimal HTML
    expect(result.success).toBe(true);
    expect(result.buffer).toBeDefined();

    console.log(`[Test] ✓ Error handling works correctly`);
  });
});
